### ISSUE TITLE
Svelte-Sidebar-Panels Advanced Example

### ISSUE THREAD

**Issue by cycle4passion** [saibotsivad/svelte-sidebar-panels#2]
I was looking for a more complex example, and found the svelte-sidebar-panels/src/demo/Demo.svelte. I put it up in a [REPL](https://svelte.dev/repl/3dcc19f3308347a4a26cd6f4e1bdb1c5?version=3.46.2).

I am still looking for....

1. Changing left and right panel widths
2. Removing the dead space between left/content/right. It looks like this is a spacer for possible scrollbars. Can it be changed to show only if needed (overflow-y: auto)
 
![image](https://user-images.githubusercontent.com/6192217/149641442-28c4484f-5311-449c-8003-8895c0abf29b.png)

3. Feature request. Instead of fully collapsing and requiring event triggers in main content area, I would like an option for a collapsed panel leaving a small/width configurable exposed edge on the screen where a mouseover auto-expands, mouseout auto-collapses. Obviously, an option for both left and right

4. Feature request. To round it out, support top and bottom panels too.

**Comment by saibotsivad** [comment]
1. To change the left/right panel widths look for `leftWidth` and `rightWidth` in the [`SidebarPanels` component](https://github.com/saibotsivad/svelte-sidebar-panels/blob/main/src/SidebarPanels.svelte).
2. Good idea, I changed `overflow-y` from `scroll` to `auto` in [v1.0.2](https://github.com/saibotsivad/svelte-sidebar-panels/releases/tag/v1.0.2) (just published now).
3. Getting this UX right across all devices is *much* more complex than most people think, and I don't think I'll get around to this any time soon. Know of any good websites/apps/etc that do a really good job of this, that I could be inspired by?
4. I can see the draw for this, but I haven't seen a real consensus in other apps as to what the exact UX would be. Again, links to sites/apps/etc for inspiration are always appreciated.
